//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_DarkImage_EnterFullScreen_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_DarkImage_EnterFullScreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_DarkImage_Exit_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_DarkImage_Exit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_DarkImage_ExitFullScreen_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_DarkImage_ExitFullScreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_DarkImage_Maximize_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_DarkImage_Maximize_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_DarkImage_Minimize_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_DarkImage_Minimize_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_DarkImage_Return_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_DarkImage_Return_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_LightImage_EnterFullScreen_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_LightImage_EnterFullScreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_LightImage_Exit_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_LightImage_Exit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_LightImage_ExitFullScreen_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_LightImage_ExitFullScreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_LightImage_Maximize_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_LightImage_Maximize_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_LightImage_Minimize_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_LightImage_Minimize_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Active_LightImage_Return_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Active_LightImage_Return_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_DarkImage_EnterFullScreen_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_DarkImage_EnterFullScreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_DarkImage_Exit_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_DarkImage_Exit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_DarkImage_ExitFullScreen_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_DarkImage_ExitFullScreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_DarkImage_Maximize_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_DarkImage_Maximize_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_DarkImage_Minimize_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_DarkImage_Minimize_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_DarkImage_Return_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_DarkImage_Return_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_LightImage_EnterFullScreen_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_LightImage_EnterFullScreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_LightImage_Exit_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_LightImage_Exit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_LightImage_ExitFullScreen_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_LightImage_ExitFullScreen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_LightImage_Maximize_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_LightImage_Maximize_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_LightImage_Minimize_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_LightImage_Minimize_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ControlBox_Inactive_LightImage_Return_16 {
            get {
                object obj = ResourceManager.GetObject("ControlBox_Inactive_LightImage_Return_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MenuItem_Exit_16 {
            get {
                object obj = ResourceManager.GetObject("MenuItem_Exit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MenuItem_Maximize_16 {
            get {
                object obj = ResourceManager.GetObject("MenuItem_Maximize_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MenuItem_Minimize_16 {
            get {
                object obj = ResourceManager.GetObject("MenuItem_Minimize_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MenuItem_Return_16 {
            get {
                object obj = ResourceManager.GetObject("MenuItem_Return_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
